### ISSUE TITLE
Very sensitive when data is constant for awhile

### ISSUE THREAD

**Issue by jasondborneman** [MicahParks/peakdetect#3] opened 2023-05-04 18:35 UTC
First off, thanks for writing this tool up based on the StackOverflow thread. This sounded like just what I need. 

Unfortunately, I'm seeing behavior that... well, may be expected but hurts usability for me. Curious how to tweak this to hopefully suit my needs as I'm not well versed in teh statistics behind the various settings (lag, threshold, and influence)

My data is basically ~360 data points. The data can stay at the same value for awhile but then ramp up or down on a curve. What I'm looking for is big (violent? 🤣) PEAKS or VALLEYS in the data. Unfortunately, the first ~37 data points in my testing data (pulled from real data I'll be checking) is a constant value. So then on point 38, even though it only goes from 5 down to 4.88, it shows it as a negative signal. Then it stays at 4.88 for a long time, causing more signals later when it curves.

[Here's my example data](https://gist.github.com/jasondborneman/3bed23da24a69cf6cae95c43a4654e98) I've been processing. I had to set threshold to **375** to even get it down to two signals. At more reasonable/smaller values it finds like 320. I think it's because things stay steady, with some gentle curves up/down at the end.

![image](https://user-images.githubusercontent.com/49321691/236294443-3c138b48-ccae-4fa5-a6a7-7e145f6e3834.png)

Lag: 30
Threshold: 375
Influence 1.0
Signals: 2

Lag: 30
Threshold: 3.5 (per examples and stuff)
Influence: 1.0 
Signals: 9

Thanks for any feedback/input/ideas you may have!

Update: ANd now I can't reproduce the 320 anomaly settings. 🤷🏻 but still, this data is an example of something I wouldn't call as having any peaks or valleys worth noting for this data. If you have any ideas how to tweak the settings and still make it responsive to big swings, I'm all ears.

**Comment by MicahParks** [comment] 2023-05-04 21:05
Based on the [uploaded CSV](https://gist.github.com/jasondborneman/3bed23da24a69cf6cae95c43a4654e98) it looks like the `Lag` parameter is what most needs adjusting. Since this algorithm works based on z-scores, it requires variance in the `Lag` period to work. If you set the `Lag` to `30` and the same value appears 30 times in a row, the next value that is not equivalent to that value will cause a peak because it is the only variance in the `Lag` period. I noticed the same value appears 207 times in a row in the given CSV. Since the CSV only contains 361 rows, I would recommend using a much larger CSV and starting out with a `Lag` larger than `250`.

You will need to tune the `Lag` and other parameters based on a larger example set of data and knowledge about what your data should look like. Here's an example:
The data in the CSV file looks like sensor data, let's say it's `[time, temperature]`. From this, I want to detect when there is a temperature spike that isn't caused by the day/night cycle. Maybe I've found out that it's unusual for the temperature to change more than 1 °C in the span of 15 minutes and it's not uncommon for my sensors to report the exact same numeric value for 30 minutes strait. I could use that information, observing a plot of temperature and peak signals on the same graph to determine an appropriate `Influence`, `Threshold`, and `Lag`. In this example, I would tune my parameters based on at least a year's worth of data.

Also consider that this Go package is for "realtime timeseries data". I don't know about the use case, but perhaps another algorithm would suit it better.

I hope this helped a bit. I'm going to close this issue as it's related to a specific use case, not the `peakdetect` project itself. If you need more assistance, feel free to hire some of my time as a freelancer. There's a contact form on [my website](https://micahparks.com/).

**Closed as completed by MicahParks** 2023-05-04 21:05 UTC

**Comment by jasondborneman** [comment] 2023-05-05 12:52
Thanks! I was hoping this would be suitable but yeah with the constraints of my system it might not be.
